// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TennisSim.Data;

#nullable disable

namespace TennisSim.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241226121235_Fourth")]
    partial class Fourth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TennisSim.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("TennisSim.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Player1Id")
                        .HasColumnType("int");

                    b.Property<int>("Player2Id")
                        .HasColumnType("int");

                    b.Property<string>("Round")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("TournamentId");

                    b.HasIndex("WinnerId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("TennisSim.Models.MatchStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Aces")
                        .HasColumnType("int");

                    b.Property<int>("DoubleFaults")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("UnforcedErrors")
                        .HasColumnType("int");

                    b.Property<int>("Winners")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchStats");
                });

            modelBuilder.Entity("TennisSim.Models.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 36,
                            Name = "China"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Congo (Congo-Brazzaville)"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Congo (Congo-Kinshasa)"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 52,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 60,
                            Name = "France"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 76,
                            Name = "India"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Korea North"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Korea South"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Myanmar (Burma)"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 124,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 128,
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 148,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 160,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 161,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 183,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 184,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 185,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("TennisSim.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NationalityId")
                        .HasColumnType("int");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<int>("YearOfBirth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NationalityId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TennisSim.Models.PlayerAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerAttributes");
                });

            modelBuilder.Entity("TennisSim.Models.PlayerCoach", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PlayerId", "CoachId");

                    b.HasIndex("CoachId");

                    b.ToTable("PlayerCoaches");
                });

            modelBuilder.Entity("TennisSim.Models.PlayerInjuryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InjuryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InjuryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RecoveryTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerInjuryHistory");
                });

            modelBuilder.Entity("TennisSim.Models.PointDistribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Round")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PointDistribution");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Points = 2000,
                            Round = "W"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Points = 1300,
                            Round = "F"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            Points = 780,
                            Round = "SF"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            Points = 430,
                            Round = "QF"
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            Points = 240,
                            Round = "R16"
                        },
                        new
                        {
                            Id = 6,
                            Category = 0,
                            Points = 130,
                            Round = "R32"
                        },
                        new
                        {
                            Id = 7,
                            Category = 0,
                            Points = 70,
                            Round = "R64"
                        },
                        new
                        {
                            Id = 8,
                            Category = 0,
                            Points = 10,
                            Round = "R128"
                        },
                        new
                        {
                            Id = 9,
                            Category = 0,
                            Points = 40,
                            Round = "Q"
                        },
                        new
                        {
                            Id = 10,
                            Category = 0,
                            Points = 10,
                            Round = "Q1"
                        },
                        new
                        {
                            Id = 11,
                            Category = 0,
                            Points = 20,
                            Round = "Q2"
                        },
                        new
                        {
                            Id = 12,
                            Category = 0,
                            Points = 30,
                            Round = "Q3"
                        },
                        new
                        {
                            Id = 13,
                            Category = 1,
                            Points = 1000,
                            Round = "W"
                        },
                        new
                        {
                            Id = 14,
                            Category = 1,
                            Points = 650,
                            Round = "F"
                        },
                        new
                        {
                            Id = 15,
                            Category = 1,
                            Points = 390,
                            Round = "SF"
                        },
                        new
                        {
                            Id = 16,
                            Category = 1,
                            Points = 215,
                            Round = "QF"
                        },
                        new
                        {
                            Id = 17,
                            Category = 1,
                            Points = 120,
                            Round = "R16"
                        },
                        new
                        {
                            Id = 18,
                            Category = 1,
                            Points = 65,
                            Round = "R32"
                        },
                        new
                        {
                            Id = 19,
                            Category = 1,
                            Points = 35,
                            Round = "R64"
                        },
                        new
                        {
                            Id = 20,
                            Category = 1,
                            Points = 10,
                            Round = "R128"
                        },
                        new
                        {
                            Id = 21,
                            Category = 1,
                            Points = 30,
                            Round = "Q"
                        },
                        new
                        {
                            Id = 22,
                            Category = 1,
                            Points = 10,
                            Round = "Q1"
                        },
                        new
                        {
                            Id = 23,
                            Category = 1,
                            Points = 20,
                            Round = "Q2"
                        },
                        new
                        {
                            Id = 24,
                            Category = 1,
                            Points = 30,
                            Round = "Q3"
                        },
                        new
                        {
                            Id = 25,
                            Category = 2,
                            Points = 500,
                            Round = "W"
                        },
                        new
                        {
                            Id = 26,
                            Category = 2,
                            Points = 325,
                            Round = "F"
                        },
                        new
                        {
                            Id = 27,
                            Category = 2,
                            Points = 195,
                            Round = "SF"
                        },
                        new
                        {
                            Id = 28,
                            Category = 2,
                            Points = 108,
                            Round = "QF"
                        },
                        new
                        {
                            Id = 29,
                            Category = 2,
                            Points = 60,
                            Round = "R16"
                        },
                        new
                        {
                            Id = 30,
                            Category = 2,
                            Points = 32,
                            Round = "R32"
                        },
                        new
                        {
                            Id = 31,
                            Category = 2,
                            Points = 1,
                            Round = "R64"
                        },
                        new
                        {
                            Id = 32,
                            Category = 2,
                            Points = 25,
                            Round = "Q"
                        },
                        new
                        {
                            Id = 33,
                            Category = 2,
                            Points = 13,
                            Round = "Q1"
                        },
                        new
                        {
                            Id = 34,
                            Category = 2,
                            Points = 18,
                            Round = "Q2"
                        },
                        new
                        {
                            Id = 35,
                            Category = 3,
                            Points = 250,
                            Round = "W"
                        },
                        new
                        {
                            Id = 36,
                            Category = 3,
                            Points = 163,
                            Round = "F"
                        },
                        new
                        {
                            Id = 37,
                            Category = 3,
                            Points = 98,
                            Round = "SF"
                        },
                        new
                        {
                            Id = 38,
                            Category = 3,
                            Points = 54,
                            Round = "QF"
                        },
                        new
                        {
                            Id = 39,
                            Category = 3,
                            Points = 30,
                            Round = "R16"
                        },
                        new
                        {
                            Id = 40,
                            Category = 3,
                            Points = 1,
                            Round = "R32"
                        },
                        new
                        {
                            Id = 41,
                            Category = 3,
                            Points = 18,
                            Round = "Q"
                        },
                        new
                        {
                            Id = 42,
                            Category = 3,
                            Points = 12,
                            Round = "Q1"
                        },
                        new
                        {
                            Id = 43,
                            Category = 3,
                            Points = 1,
                            Round = "Q2"
                        },
                        new
                        {
                            Id = 44,
                            Category = 4,
                            Points = 100,
                            Round = "W"
                        },
                        new
                        {
                            Id = 45,
                            Category = 4,
                            Points = 65,
                            Round = "F"
                        },
                        new
                        {
                            Id = 46,
                            Category = 4,
                            Points = 39,
                            Round = "SF"
                        },
                        new
                        {
                            Id = 47,
                            Category = 4,
                            Points = 21,
                            Round = "QF"
                        },
                        new
                        {
                            Id = 48,
                            Category = 4,
                            Points = 12,
                            Round = "R16"
                        },
                        new
                        {
                            Id = 49,
                            Category = 4,
                            Points = 7,
                            Round = "R32"
                        },
                        new
                        {
                            Id = 50,
                            Category = 4,
                            Points = 5,
                            Round = "Q"
                        },
                        new
                        {
                            Id = 51,
                            Category = 4,
                            Points = 3,
                            Round = "Q1"
                        },
                        new
                        {
                            Id = 52,
                            Category = 4,
                            Points = 5,
                            Round = "Q2"
                        },
                        new
                        {
                            Id = 53,
                            Category = 4,
                            Points = 7,
                            Round = "Q3"
                        },
                        new
                        {
                            Id = 54,
                            Category = 5,
                            Points = 50,
                            Round = "W"
                        },
                        new
                        {
                            Id = 55,
                            Category = 5,
                            Points = 33,
                            Round = "F"
                        },
                        new
                        {
                            Id = 56,
                            Category = 5,
                            Points = 20,
                            Round = "SF"
                        },
                        new
                        {
                            Id = 57,
                            Category = 5,
                            Points = 11,
                            Round = "QF"
                        },
                        new
                        {
                            Id = 58,
                            Category = 5,
                            Points = 6,
                            Round = "R16"
                        },
                        new
                        {
                            Id = 59,
                            Category = 5,
                            Points = 3,
                            Round = "R32"
                        },
                        new
                        {
                            Id = 60,
                            Category = 5,
                            Points = 2,
                            Round = "Q"
                        },
                        new
                        {
                            Id = 61,
                            Category = 5,
                            Points = 1,
                            Round = "Q1"
                        },
                        new
                        {
                            Id = 62,
                            Category = 5,
                            Points = 2,
                            Round = "Q2"
                        },
                        new
                        {
                            Id = 63,
                            Category = 5,
                            Points = 3,
                            Round = "Q3"
                        },
                        new
                        {
                            Id = 64,
                            Category = 6,
                            Points = 25,
                            Round = "W"
                        },
                        new
                        {
                            Id = 65,
                            Category = 6,
                            Points = 16,
                            Round = "F"
                        },
                        new
                        {
                            Id = 66,
                            Category = 6,
                            Points = 9,
                            Round = "SF"
                        },
                        new
                        {
                            Id = 67,
                            Category = 6,
                            Points = 5,
                            Round = "QF"
                        },
                        new
                        {
                            Id = 68,
                            Category = 6,
                            Points = 3,
                            Round = "R16"
                        },
                        new
                        {
                            Id = 69,
                            Category = 6,
                            Points = 2,
                            Round = "R32"
                        },
                        new
                        {
                            Id = 70,
                            Category = 6,
                            Points = 1,
                            Round = "Q"
                        },
                        new
                        {
                            Id = 71,
                            Category = 6,
                            Points = 1,
                            Round = "Q1"
                        },
                        new
                        {
                            Id = 72,
                            Category = 6,
                            Points = 2,
                            Round = "Q2"
                        },
                        new
                        {
                            Id = 73,
                            Category = 6,
                            Points = 3,
                            Round = "Q3"
                        },
                        new
                        {
                            Id = 74,
                            Category = 7,
                            Points = 10,
                            Round = "W"
                        },
                        new
                        {
                            Id = 75,
                            Category = 7,
                            Points = 6,
                            Round = "F"
                        },
                        new
                        {
                            Id = 76,
                            Category = 7,
                            Points = 4,
                            Round = "SF"
                        },
                        new
                        {
                            Id = 77,
                            Category = 7,
                            Points = 2,
                            Round = "QF"
                        },
                        new
                        {
                            Id = 78,
                            Category = 7,
                            Points = 1,
                            Round = "R16"
                        },
                        new
                        {
                            Id = 79,
                            Category = 7,
                            Points = 1,
                            Round = "R32"
                        },
                        new
                        {
                            Id = 80,
                            Category = 7,
                            Points = 1,
                            Round = "Q"
                        },
                        new
                        {
                            Id = 81,
                            Category = 7,
                            Points = 1,
                            Round = "Q1"
                        },
                        new
                        {
                            Id = 82,
                            Category = 7,
                            Points = 1,
                            Round = "Q2"
                        },
                        new
                        {
                            Id = 83,
                            Category = 7,
                            Points = 1,
                            Round = "Q3"
                        });
                });

            modelBuilder.Entity("TennisSim.Models.Ranking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Rankings");
                });

            modelBuilder.Entity("TennisSim.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("TennisSim.Models.TrainingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("PlayerId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("TennisSim.Models.Match", b =>
                {
                    b.HasOne("TennisSim.Models.Player", "Player1")
                        .WithMany("MatchesAsPlayer1")
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TennisSim.Models.Player", "Player2")
                        .WithMany("MatchesAsPlayer2")
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TennisSim.Models.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TennisSim.Models.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Tournament");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("TennisSim.Models.MatchStat", b =>
                {
                    b.HasOne("TennisSim.Models.Match", "Match")
                        .WithMany("MatchStats")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TennisSim.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TennisSim.Models.Player", b =>
                {
                    b.HasOne("TennisSim.Models.Nationality", "Nationality")
                        .WithMany("Players")
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("TennisSim.Models.PlayerAttribute", b =>
                {
                    b.HasOne("TennisSim.Models.Player", "Player")
                        .WithMany("Attributes")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TennisSim.Models.PlayerCoach", b =>
                {
                    b.HasOne("TennisSim.Models.Coach", "Coach")
                        .WithMany("PlayerCoaches")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TennisSim.Models.Player", "Player")
                        .WithMany("PlayerCoaches")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TennisSim.Models.PlayerInjuryHistory", b =>
                {
                    b.HasOne("TennisSim.Models.Player", "Player")
                        .WithMany("InjuryHistory")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TennisSim.Models.Ranking", b =>
                {
                    b.HasOne("TennisSim.Models.Player", "Player")
                        .WithMany("Rankings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TennisSim.Models.TrainingSession", b =>
                {
                    b.HasOne("TennisSim.Models.Coach", "Coach")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TennisSim.Models.Player", "Player")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TennisSim.Models.Coach", b =>
                {
                    b.Navigation("PlayerCoaches");

                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("TennisSim.Models.Match", b =>
                {
                    b.Navigation("MatchStats");
                });

            modelBuilder.Entity("TennisSim.Models.Nationality", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("TennisSim.Models.Player", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("InjuryHistory");

                    b.Navigation("MatchesAsPlayer1");

                    b.Navigation("MatchesAsPlayer2");

                    b.Navigation("PlayerCoaches");

                    b.Navigation("Rankings");

                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("TennisSim.Models.Tournament", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
